version: '3'

services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks/:/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks
  